apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          ports:
            - containerPort: 5000
