apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 236230997345.dkr.ecr.us-east-1.amazonaws.com/mp-backend:latest
          ports:
            - containerPort: 5000
